// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eczbwgkebhckysgrqfdg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjemJ3Z2tlYmhja3lzZ3JxZmRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2Mzc1NDcsImV4cCI6MjA2NzIxMzU0N30.8XdflIzn_PBewjfxcNw_8e1OatF8P-MIycDbcQZoXCU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});